name: CI

on:
  push:
    branches: "master"

jobs:
  run:
    name: Pangeo-Forge CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Setup Python
        uses: actions/setup-python@v2.1.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install -r requirements.txt
      - name: Run Pipeline
        run: |
            # stand in for pangeo-smithy runner
            python run.py
